create table if not exists public."Settings" (
  id smallint primary key default 1 check (id = 1),
  message_limit smallint not null default 10 check (message_limit in (10, 15, 20, 25, 30)),
  updated_at timestamptz not null default now()
);

insert into public."Settings" (id, message_limit)
values (1, 10)
on conflict (id) do nothing;

create table if not exists public."VIP_Users" (
  telegram_id bigint primary key,
  created_at timestamptz not null default now()
);

create table if not exists public."Pinned_Chats" (
  telegram_id bigint primary key,
  created_at timestamptz not null default now()
);

create table if not exists public."Users" (
  telegram_id bigint primary key,
  username text,
  phone text,
  first_name text,
  last_name text,
  display_name text not null,
  avatar_url text,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."Messages" (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  chat_id bigint not null,
  sender text not null default 'user' check (sender in ('user', 'bot')),
  text text,
  media_file_id text,
  media_type text,
  media_storage_path text,
  media_mime_type text,
  media_size integer,
  timestamp timestamptz not null default now()
);

alter table public."Settings"
  add column if not exists updated_at timestamptz not null default now();

alter table public."Users"
  add column if not exists username text,
  add column if not exists phone text,
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists display_name text,
  add column if not exists avatar_url text,
  add column if not exists last_seen_at timestamptz not null default now(),
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

update public."Users"
set display_name = coalesce(nullif(display_name, ''), username, first_name, 'User ' || telegram_id::text)
where display_name is null or display_name = '';

alter table public."Users"
  alter column display_name set not null;

alter table public."Messages"
  add column if not exists sender text not null default 'user',
  add column if not exists media_file_id text,
  add column if not exists media_type text,
  add column if not exists media_storage_path text,
  add column if not exists media_mime_type text,
  add column if not exists media_size integer,
  add column if not exists timestamp timestamptz not null default now();

update public."Messages"
set sender = 'user'
where sender is null or sender not in ('user', 'bot');

alter table public."Messages"
  alter column sender set default 'user',
  alter column sender set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'messages_sender_check'
      and conrelid = 'public."Messages"'::regclass
  ) then
    alter table public."Messages"
      add constraint messages_sender_check check (sender in ('user', 'bot'));
  end if;
end;
$$;

alter table public."Settings" enable row level security;
alter table public."VIP_Users" enable row level security;
alter table public."Pinned_Chats" enable row level security;
alter table public."Users" enable row level security;
alter table public."Messages" enable row level security;

create index if not exists messages_user_timestamp_desc_idx
  on public."Messages" (user_id, timestamp desc, id desc);

create index if not exists messages_user_timestamp_asc_idx
  on public."Messages" (user_id, timestamp asc, id asc);

create index if not exists messages_chat_timestamp_desc_idx
  on public."Messages" (chat_id, timestamp desc, id desc);

create index if not exists users_username_idx
  on public."Users" (lower(username));

create index if not exists users_phone_idx
  on public."Users" (phone);

create or replace view public."Chat_List" as
select distinct on (m.user_id)
  m.user_id,
  m.chat_id,
  u.username,
  coalesce(u.display_name, 'User ' || m.user_id::text) as display_name,
  u.avatar_url,
  case
    when nullif(trim(m.text), '') is not null then left(m.text, 120)
    when m.media_storage_path is not null then '[' || coalesce(m.media_type, 'media') || ']'
    when m.media_file_id is not null then '[' || coalesce(m.media_type, 'media') || ']'
    when m.media_type = 'protected_or_failed' then '[protected content]'
    else ''
  end as last_message_preview,
  m.timestamp as last_message_at,
  exists (
    select 1
    from public."Messages" media_messages
    where media_messages.user_id = m.user_id
      and media_messages.media_type is not null
  ) as has_media,
  exists (
    select 1
    from public."VIP_Users" v
    where v.telegram_id = m.user_id
  ) as is_vip,
  exists (
    select 1
    from public."Pinned_Chats" p
    where p.telegram_id = m.user_id
  ) as is_pinned
from public."Messages" m
left join public."Users" u on u.telegram_id = m.user_id
order by m.user_id, m.timestamp desc, m.id desc;

create or replace function public.set_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists settings_updated_at on public."Settings";

create trigger settings_updated_at
before update on public."Settings"
for each row
execute function public.set_settings_updated_at();

create or replace function public.set_users_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_updated_at on public."Users";

create trigger users_updated_at
before update on public."Users"
for each row
execute function public.set_users_updated_at();
