create table if not exists public."Settings" (
  id smallint primary key default 1 check (id = 1),
  message_limit smallint not null default 10 check (message_limit in (10, 15, 20, 25, 30)),
  updated_at timestamptz not null default now()
);

insert into public."Settings" (id, message_limit)
values (1, 10)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'message-media',
  'message-media',
  false,
  104857600,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'video/mp4',
    'video/webm',
    'audio/mpeg',
    'audio/mp4',
    'audio/ogg',
    'audio/opus',
    'audio/webm',
    'application/octet-stream'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public."VIP_Users" (
  telegram_id bigint primary key,
  created_at timestamptz not null default now()
);

create table if not exists public."Pinned_Chats" (
  telegram_id bigint primary key,
  created_at timestamptz not null default now()
);

create table if not exists public."Users" (
  telegram_id bigint primary key,
  username text,
  phone text,
  first_name text,
  last_name text,
  display_name text not null,
  avatar_url text,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."Messages" (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  chat_id bigint not null,
  sender text not null default 'user' check (sender in ('user', 'bot')),
  text text,
  media_file_id text,
  media_type text,
  media_storage_path text,
  media_mime_type text,
  media_size integer,
  timestamp timestamptz not null default now()
);

alter table public."Settings" enable row level security;
alter table public."VIP_Users" enable row level security;
alter table public."Pinned_Chats" enable row level security;
alter table public."Users" enable row level security;
alter table public."Messages" enable row level security;

create index if not exists messages_user_timestamp_desc_idx
  on public."Messages" (user_id, timestamp desc, id desc);

create index if not exists messages_user_timestamp_asc_idx
  on public."Messages" (user_id, timestamp asc, id asc);

create index if not exists messages_chat_timestamp_desc_idx
  on public."Messages" (chat_id, timestamp desc, id desc);

create index if not exists users_username_idx
  on public."Users" (lower(username));

create index if not exists users_phone_idx
  on public."Users" (phone);

create or replace view public."Chat_List" as
select distinct on (m.user_id)
  m.user_id,
  m.chat_id,
  u.username,
  coalesce(u.display_name, 'User ' || m.user_id::text) as display_name,
  u.avatar_url,
  case
    when nullif(trim(m.text), '') is not null then left(m.text, 120)
    when m.media_storage_path is not null then '[' || coalesce(m.media_type, 'media') || ']'
    when m.media_file_id is not null then '[' || coalesce(m.media_type, 'media') || ']'
    when m.media_type = 'protected_or_failed' then '[protected content]'
    else ''
  end as last_message_preview,
  m.timestamp as last_message_at,
  exists (
    select 1
    from public."Messages" media_messages
    where media_messages.user_id = m.user_id
      and media_messages.media_type is not null
  ) as has_media,
  exists (
    select 1
    from public."VIP_Users" v
    where v.telegram_id = m.user_id
  ) as is_vip,
  exists (
    select 1
    from public."Pinned_Chats" p
    where p.telegram_id = m.user_id
  ) as is_pinned
from public."Messages" m
left join public."Users" u on u.telegram_id = m.user_id
order by m.user_id, m.timestamp desc, m.id desc;

create or replace function public.set_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists settings_updated_at on public."Settings";

create trigger settings_updated_at
before update on public."Settings"
for each row
execute function public.set_settings_updated_at();

create or replace function public.set_users_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_updated_at on public."Users";

create trigger users_updated_at
before update on public."Users"
for each row
execute function public.set_users_updated_at();
